### ISSUE TITLE
Parameter validation

### ISSUE THREAD

**Issue by shadycuz** [DontShaveTheYak/cloud-radar#202]
The template should provide some kinda parameter validation. Like checking if a given regex is followed or if a value is allowed via the allowed values.

**Comment by dhutchison** [comment]
It looks like you've merged my PR into a release for part of this area. Are you wanting to keep this open until AWS parameter types are validated too? (I'd made a start on it but got busy)

**Comment by shadycuz** [comment]
@dhutchison I think we can keep it open since its not fully implemented, but we have a link to the PR and your comment so we have the history =)

I wasn't thinking about all these different areas of validation though, your PR covered what I had originally expected fro the feature.

**Comment by dhutchison** [comment]
It looks like there are actually 2 types of parameters still to handle:

1. [AWS-specific parameter types](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#aws-specific-parameter-types), which #239 should hopefully address (once I/someone can double check the regexes)
2. [SSM parameter types](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#aws-ssm-parameter-types). These are an interesting one - as well as verifying that the parameter value matches the format for an SSM key, this could (and probably should) piggyback on the dynamic references work to actually resolve the parameter to a configured value

**Comment by dhutchison** [comment]
I think this one can now be closed now #274 is handled. Unless there are any other validations you think are missing?

**Comment by dhutchison** [comment]
Closing this, believe the last of this was included in [v0.10.0](https://github.com/DontShaveTheYak/cloud-radar/releases/tag/0.10.0) as the release with the final #274  in it.
