### ISSUE TITLE
Possible bug in condition handling

### ISSUE THREAD

**Issue by dhutchison** [DontShaveTheYak/cloud-radar#246]
I've started writing up some expanded examples of different types of unit testing that can be done using this library and hit an issue which I think might be a bug in how conditions are evaluated, but I'm not entirely sure yet (maybe you will see I'm just doing something stupid here). 

For this I'm trying to use example templates which are provided from awslabs (purely to avoid having to create my own examples). I was using [this template](https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/SQS/SQSStandardQueue.json) for an expanded example of conditionals. 

This is my test case so far (which is in [this branch](https://github.com/dhutchison/cloud-radar/tree/feat/unit-test-scenarios/tests/test_cf/test_examples/unit/sqs_example)):

```python
import json
from pathlib import Path

import pytest

from cloud_radar.cf.unit import Template


@pytest.fixture
def template():
    template_path = (
        Path(__file__).parent / "../../../../templates/SQSStandardQueue.json"
    )
    with template_path.open() as f:
        template = json.load(f)
        return Template(template)


def test_params_create_dlq(template: Template):
    """
    This unit test case validates that when the parameter is supplied saying a DLQ
    should be created, that it is
    """
    stack = template.create_stack({"UsedeadletterQueue": "true"})

    # assert that resources have been created
    stack.has_resource("SQSQueue"), "Queue was expected to be created"
    stack.has_resource("MyDeadLetterQueue"), "DLQ was expected to be created"

```

This is failing however with this error:
```
===================================================== FAILURES =====================================================
______________________________________________ test_params_create_dlq ______________________________________________

template = <cloud_radar.cf.unit._template.Template object at 0x103eced10>

    def test_params_create_dlq(template: Template):
        """
        This unit test case validates that when the parameter is supplied saying a DLQ
        should be created, that it is
        """
>       stack = template.create_stack({"UsedeadletterQueue": "true"})

tests/test_cf/test_examples/unit/sqs_example/test_conditions.py:24: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/cloud_radar/cf/unit/_template.py:201: in create_stack
    self.render(params)
src/cloud_radar/cf/unit/_template.py:135: in render
    self.template = self.remove_condtional_resources(self.template)
src/cloud_radar/cf/unit/_template.py:182: in remove_condtional_resources
    if not is_conditional(r_value):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

data = True

    def is_conditional(data: dict) -> bool:
>       if "Condition" in data:
E       TypeError: argument of type 'bool' is not iterable

src/cloud_radar/cf/unit/_template.py:651: TypeError
============================================= short test summary info ==============================================
FAILED tests/test_cf/test_examples/unit/sqs_example/test_conditions.py::test_params_create_dlq - TypeError: argument of type 'bool' is not iterable
=========================================== 1 failed, 3 passed in 0.14s ============================================
```

I've confirmed that this issue only seems to arise if a resource does not have a `Properties` field. Changing the resource in the template to this makes the test succeed.

```
       "MyDeadLetterQueue": {
            "Condition": "CreateDeadLetterQueue",
            "Type": "AWS::SQS::Queue",
            "Properties": {
                "FifoQueue": "false"
            }
        }
```

**Comment by shadycuz** [comment]
I will look into this right now, I happen to be free, but it is likely a bug. The rendering of conditions has been tricky. I explain it a bit in #162  and #199.

**Comment by shadycuz** [comment]
I'm not even sure how this bug made it out 😞. I wonder if its happening in every template or just an edge case. 

What I am seeing is that for the resources that have a condition key, and that condition is `True`. Then the value for those resources are being change to the value of the condition. 

So:
```yaml
MyDeadLetterQueue:
  Condition: CreateDeadLetterQueue
  Type: AWS::SQS::Queue
```

Becomes:
```yaml
MyDeadLetterQueue: true
```

After the template goes through the resolved_values function. Still investigating why.

**Comment by shadycuz** [comment]
Can confirm it's some kinda edge case. We test basic condition rendering in `test_examples/test_unit.py` in the `test_log_retain` function.

**Comment by dhutchison** [comment]
Might be as simple as this (based on my understanding of the code)

```
diff --git a/src/cloud_radar/cf/unit/_template.py b/src/cloud_radar/cf/unit/_template.py
index 5f645fa..b94d517 100644
--- a/src/cloud_radar/cf/unit/_template.py
+++ b/src/cloud_radar/cf/unit/_template.py
@@ -151,6 +151,13 @@ class Template:
                 continue
 
             for r_name, r_value in get_section_items(template, section):
+
+                if section == "Resources" and "Properties" not in r_value:
+                    # While the Properties key is technically optional, 
+                    # our processing requires it to be there to distinguish
+                    # this as a Resource when we perform further rendering
+                    r_value["Properties"] = {}
+
                 if is_conditional(r_value):
                     condition_value = get_condition_value(
                         r_value["Condition"], template["Conditions"]
```

It certainly makes my test pass with no change to the `tests/test_cf/test_unit` tests, but it's only based on my brief understanding of what that rendering code is doing. It'll be a few days before I'm able to create a PR for this,  so if you want to pick it up in the mean time please do :).

**Comment by dhutchison** [comment]
I'd also edited my original comment probably during you actually replying (hadn't noticed). Narrowed down why it was an edge case in the original post. I imagine there are few resources that the whole `Properties` block ends up optional.

**Comment by shadycuz** [comment]
Yeah.... so now it's clear to me.

When we parse a template the intrinsic functions, regardless if they are in the long form or short form, get turned into dictionaries, where the key is in the longform. 

`!Ref SomeParam` would be come `{"Fn::Ref": "SomeParam"}`

Which is would be awsome... except it doesn't do it for conditions. Conditions actually come in 3 flavors. 

1. There are conditions in the `Condition` section.
```yaml
Conditions:
  Foo: !Equals ["Bar", !Ref someParam]
  ```
2. There are conditional resources
  ```yaml
MyResource:
  Condition: Foo
```
3.  There is an intrinsic condition, which I didn't even know about for a long time and is the source of this and many other bugs.
```
Conditions:
  Foo: !Equals ["Bar", !Ref someParam]
  Bar: !Not !Condition Foo
```

Here the `Bar` condition will be the opposite of whatever `Foo` is. Note that in the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-condition.html) the full function name is `Condition` and not `Fn::Condition`. Which means when we render the template we have to catch these intrinsic functions while being able to tell them apart from any other Key that is `Condition`... like in IAM policies and whatnot.... 

I like your fix above, it's very simple with no side effects and will get the job done. Another way to fix it would be to store the previous data as a parameter in the `resolve_values` recursive function. That way you could look at it and see if you are currently "inside" an intrinsic function or outside of one. Which would let us probably determine if the key "Conidition" needed any processing or not.

The way I would like to fix it, is to re-write most of resolve_values. Turn it into a generator that walks every value in a dictionary, including nested data structures. Maybe one day. Until then I will commit your fix.

**Comment by shadycuz** [comment]
@dhutchison I want to advertise all the new features you added soon. I was actually going to do it today, but the GitHub outage prevented me from copying any links. Maybe Friday or Monday. I usually post on Linkedin, twitter and Reddit on r/devops. 

I'm glad I didn't because we can fix this bug. I don't have a big social media following, so I just hope someone who does reposts it lol.

I would also like to invite you to https://github.com/DontShaveTheYak There wouldn't be any additional expectations for you to contribute. But it would allow me to tag you on PR's to review them, which I will do from time to time, for example on #247. I created DontShaveTheYak several years ago, the idea was to turn it into something similar like https://github.com/linuxserver but they focus on Home type stuff and I was to focus on infra/devops type stuff. 

Let me know what ya think =)

**Comment by dhutchison** [comment]
I'd be up for that. I'm enjoying contributing to this, seems like a great project with a lot of potential to fill the Cloudformation testing gap :)

**Comment by shadycuz** [comment]
Closing this now since its been fixed, but the other night I was almost asleep and something in the back of my lizard brain whispered to me... "You should have just checked for the Type key, it's required for all resources". 🤣
