### ISSUE TITLE
An example?

### ISSUE THREAD

**Issue by iainelder** [DontShaveTheYak/cloud-radar#52]
Hey, this looks really promising for setting up a stack, testing it, and tearing it down. I've managed to do this myself with pytest and boto3 but if this already does all the heavy lifting then I would like to take advantage of it.

But in the README I don't see how to get started after installing the library.

What do I need to do next?

**Comment by shadycuz** [comment]
@iainelder The `Usage` Readme section has two subsections called `Unit` and `Functional`. They contain examples but you need to expand them by clicking the arrows.

![image](https://user-images.githubusercontent.com/17090999/124714137-63ddaa00-decf-11eb-9fb7-8c61d2ddfcb2.png)

I also have examples in the `test` directory. Look for tests marked `@pytest.mark.e2e` for functional examples. The unit test examples are [here](https://github.com/DontShaveTheYak/cloud-radar/blob/9fff76dd83745f37fbafafd577a313bdfd15efcb/tests/test_cf/test_unit/test_template.py#L241-L268). Now that I think about it, I should probably put these tests in their own `examples` directory so they are easier to find.

I also have a guide on how to completely test Cloudformation on my blog called [Hypermodern: Cloudformation](https://la-tech.co/post/hypermodern-cloudformation/getting-started/). This guide covers linting, unit and functional testing of a template.

**Comment by iainelder** [comment]
Ah! I didn't interpret those arrows as expandable sections. I checked the source and I see it's using an [HTML details element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details)).

(I wasn't expecting that functionality in a README! Maybe a "Click to expand" hint would be useful in the text. But you might argue that it's the job of the browser or of Github's CSS to do that :-) ).

I was skim reading the README looking for code. When I didn't find it i saw the Usage section and thought "Okay, I can use it for unit testing and functional testing, but how?".

I'll read the expanded version and the other resources in more detail when I get a moment. Thanks for the quick response.

**Comment by shadycuz** [comment]
@iainelder Well I worried this would happen. I felt like if I didn't provide a way to hide them then the readme would look way to long and intimidating. I thought about defaulting them to open but that kinds defeats their purpose. 

Now that my blog series is mostly done I will add a link to the readme as well as a hint that those arrows are expandable. 

This library has some incredibly cool features (if I do say so myself) like the unit testing parts but I haven't really advertised it, so very people know it exists. That's a long way of saying you will most likely find bugs or missing features. Just open issues =) 

Thanks
